/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as DsaRouteImport } from './routes/dsa'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BrandforgeRouteImport } from './routes/brandforge'
import { Route as AxiomeraRouteImport } from './routes/axiomera'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaRoute = DsaRouteImport.update({
  id: '/dsa',
  path: '/dsa',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandforgeRoute = BrandforgeRouteImport.update({
  id: '/brandforge',
  path: '/brandforge',
  getParentRoute: () => rootRouteImport,
} as any)
const AxiomeraRoute = AxiomeraRouteImport.update({
  id: '/axiomera',
  path: '/axiomera',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/axiomera': typeof AxiomeraRoute
  '/brandforge': typeof BrandforgeRoute
  '/career': typeof CareerRoute
  '/dsa': typeof DsaRoute
  '/fitness': typeof FitnessRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/internships': typeof InternshipsRoute
  '/journal': typeof JournalRoute
  '/mission': typeof MissionRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/axiomera': typeof AxiomeraRoute
  '/brandforge': typeof BrandforgeRoute
  '/career': typeof CareerRoute
  '/dsa': typeof DsaRoute
  '/fitness': typeof FitnessRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/internships': typeof InternshipsRoute
  '/journal': typeof JournalRoute
  '/mission': typeof MissionRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/axiomera': typeof AxiomeraRoute
  '/brandforge': typeof BrandforgeRoute
  '/career': typeof CareerRoute
  '/dsa': typeof DsaRoute
  '/fitness': typeof FitnessRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/internships': typeof InternshipsRoute
  '/journal': typeof JournalRoute
  '/mission': typeof MissionRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/axiomera'
    | '/brandforge'
    | '/career'
    | '/dsa'
    | '/fitness'
    | '/goals'
    | '/history'
    | '/internships'
    | '/journal'
    | '/mission'
    | '/projects'
    | '/reset-password'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/axiomera'
    | '/brandforge'
    | '/career'
    | '/dsa'
    | '/fitness'
    | '/goals'
    | '/history'
    | '/internships'
    | '/journal'
    | '/mission'
    | '/projects'
    | '/reset-password'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/axiomera'
    | '/brandforge'
    | '/career'
    | '/dsa'
    | '/fitness'
    | '/goals'
    | '/history'
    | '/internships'
    | '/journal'
    | '/mission'
    | '/projects'
    | '/reset-password'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  AxiomeraRoute: typeof AxiomeraRoute
  BrandforgeRoute: typeof BrandforgeRoute
  CareerRoute: typeof CareerRoute
  DsaRoute: typeof DsaRoute
  FitnessRoute: typeof FitnessRoute
  GoalsRoute: typeof GoalsRoute
  HistoryRoute: typeof HistoryRoute
  InternshipsRoute: typeof InternshipsRoute
  JournalRoute: typeof JournalRoute
  MissionRoute: typeof MissionRoute
  ProjectsRoute: typeof ProjectsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa': {
      id: '/dsa'
      path: '/dsa'
      fullPath: '/dsa'
      preLoaderRoute: typeof DsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brandforge': {
      id: '/brandforge'
      path: '/brandforge'
      fullPath: '/brandforge'
      preLoaderRoute: typeof BrandforgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axiomera': {
      id: '/axiomera'
      path: '/axiomera'
      fullPath: '/axiomera'
      preLoaderRoute: typeof AxiomeraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  AxiomeraRoute: AxiomeraRoute,
  BrandforgeRoute: BrandforgeRoute,
  CareerRoute: CareerRoute,
  DsaRoute: DsaRoute,
  FitnessRoute: FitnessRoute,
  GoalsRoute: GoalsRoute,
  HistoryRoute: HistoryRoute,
  InternshipsRoute: InternshipsRoute,
  JournalRoute: JournalRoute,
  MissionRoute: MissionRoute,
  ProjectsRoute: ProjectsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
